### ISSUE TITLE
For v3 we do not need section as "full time | mid" in SERP for each job tile

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#109]
Please remove the text "full time | mid" from SERP from each tile

**Comment by biancacristurean** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14651)
- Test [No "full time/mid" for the displayed tiles.](https://web.testquality.com/site/peviitor/project/12763/tests?testId=399421&folderId=124506).
