### ISSUE TITLE
Google page is opened for all jobs description when click on "Vezi Jobul"

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#110]
**ENVIRONMENT**: BETA
  - url: https://beta.peviitor.ro/
  - browser: Chrome

**STEPS TO REPRODUCE**: 
1. open url in browser
2. click on input text search
3. type tester
4. hit enter
5. click on "Vezi Jobul"
6. check results

**EXPECTED RESULTS**:
   Job description for that specific opportunity is open in a new tab 

**ACTUAL RESULTS**:
   Google is opened for all jobs

**Comment by biancacristurean** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=12009)
- Test [Logo on landing page](https://web.testquality.com/site/peviitor/project/12763/tests?testId=308270&folderId=111013).
- Test [New tab opened for each opportunity.](https://web.testquality.com/site/peviitor/project/12763/tests?testId=399422&folderId=124506).
