### ISSUE TITLE
The text 'Caută' has the wrong font.

### ISSUE THREAD

**Issue by RuthSupuran** [peviitor-ro/ui-js#122]
## Precondition
URL: https://beta.peviitor.ro/
Browser: chrome
Platform: IPone 12 Pro

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Access the link in browser.

#### Expected Result
The website is opened without any problems.

### Step 2 <span style="color:#ff5538"> **[Fail]** </span>
Check the font for the text.

#### Expected Result
The font is &#x27;SP Pro&#x27;.

#### Actual Result
The font is &#x27;PoppinsLight&#x27;.

**Comment by RuthSupuran** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=11167)
- Test [[v0] no errors on server side](https://web.testquality.com/site/peviitor/project/12763/runs/164386?resultId=2876997) in Run [Run 001](https://web.testquality.com/site/peviitor/project/12763/runs/164386) (linked to Cycle [Validate API v0 for peviitor.ro](https://web.testquality.com/site/peviitor/project/12763/cycles/26136)).
- Test [The font for 'caută' is 'SF Pro'.](https://web.testquality.com/site/peviitor/project/12763/runs/171695?resultId=3024778) in Run [Run 042](https://web.testquality.com/site/peviitor/project/12763/runs/171695) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by 12Cristi** [comment]
Duplicate bug
