### ISSUE TITLE
You can not click the 'remote' button.

### ISSUE THREAD

**Issue by RuthSupuran** [peviitor-ro/ui-js#123]
## Precondition
URL: https://beta.peviitor.ro
Device: Iphone 12 Pro
Browser: Chrome

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Open URL in browser

#### Expected Result
The webpage is loaded without any errors

### Step 2 <span style="color:#ff5538"> **[Block]** </span>
Check if the &quot;remote&quot; button is clickable 

#### Expected Result
You can click the &quot;remote&quot; button

### Step 3 <span style="color:#ff9000"> **[Pending]** </span>
Check if clicking the &quot;remote&quot; button opens a dropdown menu 

#### Expected Result
Clicking the &quot;remote&quot; button succesfully displays 3 options - &quot;dupa orase&quot;, &quot;dupa industrie&quot;, &quot;dupa pozitie&quot;

**Comment by RuthSupuran** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12394)
- Test [Clicking the "remote" button opens a dropdown menu ](https://web.testquality.com/site/peviitor/project/12763/runs/171695?resultId=3024713) in Run [Run 042](https://web.testquality.com/site/peviitor/project/12763/runs/171695) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by sebiboga** [comment]
For first sub-version this is accepted not to work
