### ISSUE TITLE
The text 'Toată România' is missing from the search box

### ISSUE THREAD

**Issue by RuthSupuran** [peviitor-ro/ui-js#127]
## Precondition
URL: https://beta.peviitor.ro/
Browser: chrome
Platform: IPone 12 Pro

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Access the link in browser.

#### Expected Result
The website is opened without any problems.

### Step 2 <span style="color:#ff5538"> **[Fail]** </span>
Check the text in the secon search bar.

#### Expected Result
The text &#x27;Toată România&#x27; is present.

**Comment by dan86-coder** [comment]
Duplicate in run042.
