### ISSUE TITLE
The first search bar has the height of 46px.

### ISSUE THREAD

**Issue by RuthSupuran** [peviitor-ro/ui-js#131]
## Precondition
URL: https://beta.peviitor.ro/
Browser: Chrome
Platform: IPhone 12 Pro

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Open link in browser.

#### Expected Result
The website is opened without any problems.

### Step 2 <span style="color:#ff5538"> **[Fail]** </span>
Check the height of the search bar.

#### Expected Result
The first search bar has the height of 48px.

#### Actual Result
The first search bar has the height of 46px.

**Comment by RuthSupuran** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12403)
- Test [The first search bar has the height of 48px.](https://web.testquality.com/site/peviitor/project/12763/runs/171695?resultId=3024843) in Run [Run 042](https://web.testquality.com/site/peviitor/project/12763/runs/171695) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by dan86-coder** [comment]
Duplicate.
