### ISSUE TITLE
The briefcase icon width is 20px

### ISSUE THREAD

**Issue by biancacristurean** [peviitor-ro/ui-js#147]
## Precondition
URL: https://beta.peviitor.ro/
Device: Samsung Galaxy S21 Ultra 
Browser: Chrome
Platform: Android 12

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Open URL in browser

#### Expected Result
Website is loaded without any issues 

### Step 2 <span style="color:#ff5538"> **[Fail]** </span>
Inspect witdh for briefcase icon on &quot;Alătură-te&quot; button

#### Expected Result
Witdh should be 16.67px

**Comment by biancacristurean** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12443)
- Test [Briefcase icon width](https://web.testquality.com/site/peviitor/project/12763/runs/171695?resultId=3024736) in Run [Run 042](https://web.testquality.com/site/peviitor/project/12763/runs/171695) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by dan86-coder** [comment]
It's a duplicate.
