### ISSUE TITLE
"Alătură-te" button's width is 90px

### ISSUE THREAD

**Issue by biancacristurean** [peviitor-ro/ui-js#149]
## Precondition
URL: https://beta.peviitor.ro/
Device: Samsung Galaxy S21 Ultra 
Browser: Chrome
Platform: Android 12

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Open URL in browser

#### Expected Result
Website is loaded without any issues 

### Step 2 <span style="color:#ff5538"> **[Fail]** </span>
Inspect &quot;Alătură-te&quot;  button&#x27;s width

#### Expected Result
Button&#x27;s width should be 73px

**Comment by biancacristurean** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12445)
- Test ["Alătură-te"  button width](https://web.testquality.com/site/peviitor/project/12763/runs/171695?resultId=3024746) in Run [Run 042](https://web.testquality.com/site/peviitor/project/12763/runs/171695) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by dan86-coder** [comment]
It's a duplicate.
