### ISSUE TITLE
The display of the search box is 'inline-block'

### ISSUE THREAD

**Issue by RuthSupuran** [peviitor-ro/ui-js#158]
## Precondition
URL: https://beta.peviitor.ro/
Browser: chrome
Platform: IPone 12 Pro

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Access the link in browser.

#### Expected Result
The website is opened without any problems.

### Step 2 <span style="color:#ff5538"> **[Fail]** </span>
Check the display for the search button

#### Expected Result
The display is &#x27;flex&#x27;.

#### Actual Result
The display is &#x27;inline-block&#x27;.

**Comment by RuthSupuran** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12477)
- Test [The search's button display is 'flex'.](https://web.testquality.com/site/peviitor/project/12763/runs/172020?resultId=3037307) in Run [Run 043](https://web.testquality.com/site/peviitor/project/12763/runs/172020) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by biancacristurean** [comment]
Duplicate
