### ISSUE TITLE
"Alătură-te cauzei noastre" footer section text font -size does not match

### ISSUE THREAD

**Issue by dan86-coder** [peviitor-ro/ui-js#165]
## Precondition
URL: https://beta.peviitor.ro/
Device: Samsung Galaxy S21 Ultra 
Browser: Chrome
Platform: Android 12

### Step 1 <span style="color:#ff5538"> **[Pass]** </span>
Open URL in browser

#### Expected Result
 Website is loaded without any issues

### Step 2 <span style="color:#ff5538"> **[Pass]** </span>
Scroll to footer

#### Expected Result
Page is scrolled without any issues

### Step 3 <span style="color:#ff5538"> **[Fail]** </span>
Inspect &quot;Alătură-te cauzei noastre&quot;  text-size

#### Expected Result
Font size should be 14px

**Comment by dan86-coder** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12494)
- Test ["Alătură-te cauzei noastre" footer section text font - size ](https://web.testquality.com/site/peviitor/project/12763/runs/172020?resultId=3037335) in Run [Run 043](https://web.testquality.com/site/peviitor/project/12763/runs/172020) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by 12Cristi** [comment]
Duplicate bug report.
