### ISSUE TITLE
Magnifying glass not clickable

### ISSUE THREAD

**Issue by biancacristurean** [peviitor-ro/ui-js#193]
## Precondition
URL: https://beta.peviitor.ro/
Browser: chrome
Platform: IPone 12 Pro

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Access the link on your browser.

#### Expected Result
The website opens without any problems.

### Step 2 <span style="color:#58b880"> **[Pass]** </span>
Type &#x27;tester&#x27; on the first search bar.

#### Expected Result
You can type any string of words.

### Step 3 <span style="color:#ff5538"> **[Fail]** </span>
Click the magnifying glass.

#### Expected Result
By clicking the magnifying glass it redirects you to the desired search.

#### Actual Result
The magnifying glass is not clickable.

**Comment by biancacristurean** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12581)
- Test [The magnifying glass is clickable.](https://web.testquality.com/site/peviitor/project/12763/runs/172167?resultId=3045864) in Run [Run 046](https://web.testquality.com/site/peviitor/project/12763/runs/172167) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by sebiboga** [comment]
@biancacristurean please validate with OANA on Discord
