### ISSUE TITLE
The font weight for the search button "cauta" is 100 not 510

### ISSUE THREAD

**Issue by razvannterec** [peviitor-ro/ui-js#197]
## Precondition
URL: https://beta.peviitor.ro/
Browser: chrome
Platform: IPone 12 Pro

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Access link in browser.

#### Expected Result
The website is opened without any problems.

### Step 2 <span style="color:#ff5538"> **[Fail]** </span>
Check the weight of the text.

#### Expected Result
The weight of the text is 510.

#### Actual Result
The weight of the text is 100.

**Comment by 12Cristi** [comment]
Duplicate bug .
