### ISSUE TITLE
Missing dropdown from "Toată România"

### ISSUE THREAD

**Issue by biancacristurean** [peviitor-ro/ui-js#200]
## Precondition
URL: https://beta.peviitor.ro/
Browser: chrome
Platform: IPone 12 Pro

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Access the link in browser.

#### Expected Result
The website is opened without any problems.

### Step 2 <span style="color:#ff5538"> **[Fail]** </span>
Click on &#x27;Toată România&#x27;.

#### Expected Result
By clicking on &#x27;Toată România&#x27; a dropdown is present.

#### Actual Result
&quot;Toată România&quot; is missing,also the dropdown

**Comment by biancacristurean** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12599)
- Test [When you click on 'Toată România' a dropdown appears.](https://web.testquality.com/site/peviitor/project/12763/runs/172167?resultId=3045755) in Run [Run 046](https://web.testquality.com/site/peviitor/project/12763/runs/172167) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by sebiboga** [comment]
@sergiuae @sergiuavram In dropdown we will have 2 options:
Toata Romania
Toate
