### ISSUE TITLE
Different font for the text in the second search bar

### ISSUE THREAD

**Issue by biancacristurean** [peviitor-ro/ui-js#206]
## Precondition
URL: https://beta.peviitor.ro/
Browser: chrome
Platform: IPone 12 Pro

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Access the link in your browser.

#### Expected Result
The website is opened without any problems.

### Step 2 <span style="color:#ff5538"> **[Fail]** </span>
Check the font on the text in the second search bar.

#### Expected Result
The font on the text is &#x27;SF pro&#x27;.

#### Actual Result
The font is Poppins Light

**Comment by biancacristurean** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12608)
- Test [The text in the second search bar has the font 'SF pro'.](https://web.testquality.com/site/peviitor/project/12763/runs/172167?resultId=3045836) in Run [Run 046](https://web.testquality.com/site/peviitor/project/12763/runs/172167) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by dan86-coder** [comment]
Duplicate.
