### ISSUE TITLE
Different width for the footer divider line

### ISSUE THREAD

**Issue by biancacristurean** [peviitor-ro/ui-js#207]
## Precondition
URL: https://beta.peviitor.ro/
Device: Samsung Galaxy S21 Ultra 
Browser: Chrome
Platform: Android 12

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Open URL in browser

#### Expected Result
 Website is loaded without any issues

### Step 2 <span style="color:#58b880"> **[Pass]** </span>
Scroll to footer

#### Expected Result
Page is scrolled without any issues

### Step 3 <span style="color:#ff5538"> **[Fail]** </span>
Inspect footer dividing line 

#### Expected Result
Width should be 335px

#### Actual Result
Width is 320px

**Comment by biancacristurean** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12609)
- Test [Footer divider line width](https://web.testquality.com/site/peviitor/project/12763/runs/172167?resultId=3045843) in Run [Run 046](https://web.testquality.com/site/peviitor/project/12763/runs/172167) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by dan86-coder** [comment]
Duplicate.
