### ISSUE TITLE
Different font for "© 2022 - Toate drepturile rezervate PE VIITOR" 

### ISSUE THREAD

**Issue by biancacristurean** [peviitor-ro/ui-js#208]
## Precondition
URL: https://beta.peviitor.ro/
Device: Samsung Galaxy S21 Ultra 
Browser: Chrome
Platform: Android 12

### Step 1 <span style="color:#ff9000"> **[Pending]** </span>
Open URL in browser

#### Expected Result
 Website is loaded without any issues

### Step 2 <span style="color:#ff9000"> **[Pending]** </span>
Scroll to footer

#### Expected Result
Page is scrolled without any issues

### Step 3 <span style="color:#ff9000"> **[Pending]** </span>
Inspect &quot;© 2022 - Toate drepturile rezervate PE VIITOR&quot; text-font

#### Expected Result
Font should be &quot;SF Pro&quot;

#### Actual Result
The font is Segoe UI

**Comment by biancacristurean** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12610)
- Test ["© 2022 - Toate drepturile rezervate PE VIITOR" bottom footer section text ](https://web.testquality.com/site/peviitor/project/12763/runs/172167?resultId=3045849) in Run [Run 046](https://web.testquality.com/site/peviitor/project/12763/runs/172167) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by dan86-coder** [comment]
Duplicate.
