### ISSUE TITLE
Redirect to "Term and Condition" not working

### ISSUE THREAD

**Issue by 12Cristi** [peviitor-ro/ui-js#216]
## Precondition
URL: https://beta.peviitor.ro/
Device: Samsung Galaxy S21 Ultra 
Browser: Chrome
Platform: Android 12

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Open URL in browser

#### Expected Result
 Website is loaded without any issues

### Step 2 <span style="color:#58b880"> **[Pass]** </span>
Scroll to footer

#### Expected Result
Page is scrolled without any issues

### Step 3 <span style="color:#ff5538"> **[Fail]** </span>
Tap &quot;Condiții de utilizare&quot;

#### Expected Result
You should be redirected to &quot;Terms and conditions&quot; page (https://legal.peviitor.ro/)

#### Actual Result
The redirect link to &quot;Terms and conditions&quot; page its not set.

**Comment by 12Cristi** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12618)
- Test [Tapping on "Condiții de utilizare" footer section text](https://web.testquality.com/site/peviitor/project/12763/runs/172167?resultId=3045819) in Run [Run 046](https://web.testquality.com/site/peviitor/project/12763/runs/172167) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by biancacristurean** [comment]
fixed
