### ISSUE TITLE
The SERP page doesn't load when I press enter, after typing any word in search bar

### ISSUE THREAD

**Issue by annamserban** [peviitor-ro/ui-js#294]
## Precondition
URL: https://peviitor.ro/
Device: HP
Browser: Mozilla Firefox
Platform: Windows 10

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Open URL in browser.

#### Expected Result
Website is loaded without any issues.

### Step 2 <span style="color:#58b880"> **[Pass]** </span>
Type any word in the search bar.

#### Expected Result
That word appears in the search bar.

### Step 3 <span style="color:#ff5538"> **[Fail]** </span>
Press enter to display the SERP page.

#### Expected Result
The SERP page is loaded without any issues.

**Comment by annamserban** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=13706)
- Test [Press Enter after typing any word in search bar](https://web.testquality.com/site/peviitor/project/12763/runs/175351?resultId=3176881) in Run [Run 068](https://web.testquality.com/site/peviitor/project/12763/runs/175351) (linked to Cycle [V04 Desktop-landingpage](https://web.testquality.com/site/peviitor/project/12763/cycles/28246)).

**Comment by biancacristurean** [comment]
solved
