### ISSUE TITLE
[Landing page] fade 4 seconds

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#37]
The input text area is hidden for 4 seconds
After 4 seconds the input text search will appear
user is able to input search string after the input text search is displayed

the text with number of jobs is not displyed until search text box is displayed

**Comment by sebiboga** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14064)
- Test [Serch box appear after 4 seconds](https://web.testquality.com/site/peviitor/project/12763/tests?folderId=424164&testId=378923).

**Comment by biancacristurean** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=11267)
- Test [Serch box appear after 4 seconds](https://web.testquality.com/site/peviitor/project/12763/runs/165788?resultId=2903136) in Run [Run 037](https://web.testquality.com/site/peviitor/project/12763/runs/165788) (linked to Cycle [Landing Page](https://web.testquality.com/site/peviitor/project/12763/cycles/26405)).
