### ISSUE TITLE
[Landing page] Border of Search box

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#41]
Initially the search box is dispayed with thin border
On hover no border is displayed
On focus no border is displayed

**Comment by MargineanMihai87** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14070)
- Test [Border Search box](https://web.testquality.com/site/peviitor/project/12763/tests?folderId=424172&testId=378931).

**Comment by biancacristurean** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=11270)
- Test [Border Search box](https://web.testquality.com/site/peviitor/project/12763/runs/165788?resultId=2903142) in Run [Run 037](https://web.testquality.com/site/peviitor/project/12763/runs/165788) (linked to Cycle [Landing Page](https://web.testquality.com/site/peviitor/project/12763/cycles/26405)).
