### ISSUE TITLE
[Landing page] Delete icon for Search bar

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#42]
We need a delete icon inside Search bar to delete the text to search
Delete icon is right align

**Comment by biancacristurean** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14069)
- Test [Delete icon inside search bar.](https://web.testquality.com/site/peviitor/project/12763/tests?folderId=424171&testId=378930).

**Comment by biancacristurean** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=11269)
- Test [Delete icon inside search bar.](https://web.testquality.com/site/peviitor/project/12763/runs/165788?resultId=2903141) in Run [Run 037](https://web.testquality.com/site/peviitor/project/12763/runs/165788) (linked to Cycle [Landing Page](https://web.testquality.com/site/peviitor/project/12763/cycles/26405)).
