### ISSUE TITLE
[Landing page] Background image

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#44]
Background image is displayed as per design https://www.figma.com/file/ZnxmiUT0MBUvGFv2D3vaZz/Website-designs?node-id=0%3A1

**Comment by Danmicu555** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14068)
- Test [Background image is displayed ](https://web.testquality.com/site/peviitor/project/12763/tests?folderId=424169&testId=378928).
