### ISSUE TITLE
[Landing page] Mobile view is displayed as per design

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#45]
Mobile view is displayed as per design https://www.figma.com/file/ZnxmiUT0MBUvGFv2D3vaZz/Website-designs?node-id=0%3A1

**Comment by MargineanMihai87** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14073)
- Test [Mobile view is displayed as per design](https://web.testquality.com/site/peviitor/project/12763/tests?folderId=424175&testId=378934).
