### ISSUE TITLE
[Landing page] Page title

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#46]
peviitor - motor de cautare locuri de munca

**Comment by Danmicu555** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14097)
- Test [Page title is "peviitor - motor de cautare locuri de munca"](https://web.testquality.com/site/peviitor/project/12763/tests?folderId=424630&testId=379337).

**Comment by biancacristurean** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=11268)
- Test [Page title is "peviitor - motor de cautare locuri de munca"](https://web.testquality.com/site/peviitor/project/12763/runs/165788?resultId=2903134) in Run [Run 037](https://web.testquality.com/site/peviitor/project/12763/runs/165788) (linked to Cycle [Landing Page](https://web.testquality.com/site/peviitor/project/12763/cycles/26405)).
