### ISSUE TITLE
[SERP] Logo presented on header

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#50]
Logo is displayed on heder
Logo contains words: pe viitor
Logo have font: Just Mandrown

**Comment by Danmicu555** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14113)
- Test [Logo is presented on header](https://web.testquality.com/site/peviitor/project/12763/tests?folderId=425010&testId=379658).
