### ISSUE TITLE
[SERP] Aside section -- Filter area

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#52]
Aside title is: "Rafineaza cautarea"
Filter by "Companie"
Remote ON/OFF
"Inclusiv din afara Romaniei" ON/OFF
The design is described in Figma

**Comment by MargineanMihai87** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14175)
- Test ["Rafineaza cautarea"](https://web.testquality.com/site/peviitor/project/12763/tests?folderId=427227&testId=381625).
