### ISSUE TITLE
[SERP] display number of open positions from database

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#53]
The section for Search Results begins with:
**xx de oportunitati in Romania pentru yyy**
  where xx is number of open positions
   and yy is the string we are searching for

**Comment by MargineanMihai87** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14179)
- Test ["Display number of open positions from database"](https://web.testquality.com/site/peviitor/project/12763/tests?folderId=427231&testId=381629).
