### ISSUE TITLE
[SERP] Tile for each open position in Results Page

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#54]
Tile for presenting the open position is delimited by a border 0.5px with radius of 10px with color:  #C4C4C4, solid.

Tile contains Company
Tile contains Job Title
Tile contains location (Country, City where applicable)
Tile contains the link to the original Job Description

Title and link are clickable

Tile contains a button "Vezi jobul"
Button is clickable

distance between tiles: 14px

**Comment by sebiboga** [comment]
TBD: do we have a better suggestion for button label instead of "Vezi jobul"?

**Comment by sebiboga** [comment]
from design we do not need: "Nou" and we do not need "full-time | mid" for version v3

**Comment by biancacristurean** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14117)
- Test [Tile for presenting the open position is delimited by a border 0.5px ](https://web.testquality.com/site/peviitor/project/12763/tests?folderId=425017&testId=379665).
