### ISSUE TITLE
[SERP] Number of tiles displayed

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#55]
We display 10 tiles per page
We have a link "Mai multe joburi"
On click we show next 10 jobs

**Comment by Danmicu555** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14172)
- Test [We display 10 tiles per page](https://web.testquality.com/site/peviitor/project/12763/tests?folderId=427224&testId=381622).
