### ISSUE TITLE
[SERP] Footer

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/ui-js#56]
Footer is placed at bottom of page
Footer have 82px height with color #F8F9FA
Footer contains on the left: "© 2022 ASOCIATIA OPORTUNITATI SI CARIERE"
Footer contains in the middle the Facebook icon
Footer contains in the middle LinkedIN icon
Footer contains "Contact"
Footer contains "Despre noi"
Footer contains "Confidentialitate"
Footer contains "Termeni si Conditii"

**Comment by biancacristurean** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/peviitor/project/12763?requirementId=14129)
- Test [Footer is placed at bottom of page.](https://web.testquality.com/site/peviitor/project/12763/tests?folderId=425030&testId=379678).

**Comment by biancacristurean** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12238)
- Test [Footer color.](https://web.testquality.com/site/peviitor/project/12763/runs/168056?resultId=2952403) in Run [Run 041](https://web.testquality.com/site/peviitor/project/12763/runs/168056) (linked to Cycle [SERP](https://web.testquality.com/site/peviitor/project/12763/cycles/26406)).
